<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FleetRent.Application\FleetRent.Application.csproj" />
    <ProjectReference Include="..\FleetRent.InfraStructure\FleetRent.InfraStructure.csproj" />
    <ProjectReference Include="..\FleetRent.Persistance\FleetRent.Persistance.csproj" />
    <ProjectReference Include="..\FleetRent.Shared\FleetRent.Shared.csproj" />
  </ItemGroup>

</Project>
